<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0.show,1.Hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0.show,1.Hidden'),
        ),
    ]
=======
# Generated by Django 5.0.4 on 2024-04-24 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=False, help_text='0.show,1.Hidden'),
        ),
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.BooleanField(default=False, help_text='0.show,1.Hidden'),
        ),
    ]
>>>>>>> 7c21ed5aeb93418d1ab75479e42e840677e8decc
