<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_status_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
=======
# Generated by Django 5.0.4 on 2024-04-25 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_category_status_product_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
    ]
>>>>>>> 7c21ed5aeb93418d1ab75479e42e840677e8decc
